name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone repository
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: npm i
      -
        name: Build Image
        run: npm run build
      - 
        name: Test
        run: npm run test
      -
        name: Lint
        run: npm run lint
